package com.dev.bayan_ibrahim.news_app.utiles

enum class Countries (val code: String) {
    UNITED_ARAB_EMIRATES("ae"),
    ARGENTINA ("ar"),
    AUSTRIA ("at"),
    AUSTRALIA ("au"),
    BELGIUM ("be"),
    BULGARIA ("bg"),
    BRAZIL ("br"),
    CANADA ("ca"),
    SWITZERLAND ("ch"),
    CHINA ("cn"),
    COLOMBIA ("co"),
    CUBA ("cu"),
    CZECHIA ("cz"),
    GERMANY ("de"),
    EGYPT ("eg"),
    FRANCE ("fr"),
    UNITED_KINDOM ("gb"),
    GREECE ("gr"),
    HONG_KONG ("hk"),
    HUNGARY ("hu"),
    INDONESIA ("id"),
    IRELAND ("ie"),
    ISAEL ("il"),
    INDIA ("in"),
    ITALY ("it"),
    JAPAN ("jp"),
    KOREA ("kr"),
    LITHUANIA ("lt"),
    LATVIA ("lv"),
    MOROCCO ("ma"),
    MEXICO ("mx"),
    MALAYSIA ("my"),
    NIGEIA ("ng"),
    NETHERLAND ("nl"),
    NORWAY ("no"),
    NEW_ZEALAND ("nz"),
    PHILIPPINES ("ph"),
    POLAND ("pl"),
    PORTUGAL ("pt"),
    ROMANIA ("ro"),
    SERBIA ("rs"),
    RUSSIA("ru"),
    SAUDI_ARABIA ("sa"),
    SWEDEN ("se"),
    SOMGAPORE ("sg"),
    SLOVENIA ("si"),
    SLOVAKIA ("sk"),
    THAILAND ("th"),
    TURKEY ("tr"),
    TAIWAN ("tw"),
    UKARINE ("ua"),
    USA ("us"),
    VENEZUELA ("ve"),
    SOUTH_AFRICA ("za"),
}